config/routes.rb
Rails.application.routes.draw do
  resources :guardians
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :students
  resources :teachers

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/guardian.rb
class Guardian < ActiveRecord::Base
  has_and_belongs_to_many :students
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_and_belongs_to_many :teachers
  has_and_belongs_to_many :guardians
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_and_belongs_to_many :students
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guardians_controller.rb
class GuardiansController < ApplicationController
before_action :set_guardian, only: [:show, :edit, :update, :destroy]

  # GET /guardians
  def index
    @guardian = Guardian.all
  end

  # GET /guardians/1
  def show
  end

  # GET /guardians/new
  def new
    @guardian = Guardian.new
  end

  # GET /guardians/1/edit
  def edit
  end

  # POST /guardians
  def create
    @guardian = Guardian.new(guardian_params)

    if @guardian.save
        student = Student.find(params["student"]["guardian"])
        @guardian.student << student
        redirect_to @guardian, notice: 'Guardian was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /guardians/1
  def update
    if @guardian.update(guardian_params)
      student = Student.find(params["student"]["guardian_id"])
      @guardian.student << student
        redirect_to @guardian, notice: 'Guardian information was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /guardians/1
  def destroy
    @guardian.destroy
    redirect_to @guardians, notice: 'Student was successfully deleted.'
  end

  private
  def set_guardian
    @guardian = Guardian.find(params[:id])
  end

  def guardian_params
     params.require(:guardian).permit(:first_name, :last_name, :email)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/1
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    if @student.save
        teacher = Teacher.find(params["student"]["teacher"])
        @student.teachers << teacher
        redirect_to @student, notice: 'Student was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /students/1
  def update
    if @student.update(student_params)
      teacher = Teacher.find(params["student"]["teacher_id"])
      @student.teachers << teacher
        redirect_to @student, notice: 'Student information was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    redirect_to @students, notice: 'Student was successfully deleted.'
  end

  private
  def set_student
    @student = Student.find(params[:id])
  end

  def student_params
    params.require(:student).permit(:first_name, :last_name)
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  def create
    @teacher = Teacher.new(teacher_params)

    if @teacher.save
        redirect_to @teacher, notice: 'Teacher was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /teachers/1
  def update
    if @teacher.update(teacher_params)
        redirect_to @teacher, notice: 'Teacher information was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /teachers/1
  def destroy
    @teacher.destroy
    render :index, notice: 'Teacher was successfully deleted.'
  end

  private
  def set_teacher
    @teacher = Teacher.find(params[:id])
  end

  def teacher_params
    params.require(:teacher).permit(:first_name, :last_name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guardians_helper.rb
module GuardiansHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/guardians/_form.html.erb
<%= form_for(@guardian) do |f| %>
  <% if @guardian.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guardian.errors.count, "error") %> prohibited this guardian from being saved:</h2>

      <ul>
      <% @guardian.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guardians/edit.html.erb
<h1>Editing Guardian</h1>

<%= render 'form' %>

<%= link_to 'Show', @guardian %> |
<%= link_to 'Back', guardians_path %>

app/views/guardians/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guardians</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guardians.each do |guardian| %>
      <tr>
        <td><%= guardian.first_name %></td>
        <td><%= guardian.last_name %></td>
        <td><%= guardian.email %></td>
        <td><%= link_to 'Show', guardian %></td>
        <td><%= link_to 'Edit', edit_guardian_path(guardian) %></td>
        <td><%= link_to 'Destroy', guardian, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guardian', new_guardian_path %>

app/views/guardians/new.html.erb
<h1>New Guardian</h1>

<%= render 'form' %>

<%= link_to 'Back', guardians_path %>

app/views/guardians/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @guardian.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @guardian.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @guardian.email %>
</p>

<%= link_to 'Edit', edit_guardian_path(@guardian) %> |
<%= link_to 'Back', guardians_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PtcScheduler</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_area :last_name %>
  </div>
  <div class="field">
    <%= f.label :teacher %><br>
    <select name="student[teacher_id]">
      <% Teacher.all.each do |teacher| %>
        <option value="<%= teacher.id %>"><%= teacher.first_name %> <%= teacher.last_name %></option>
      <% end %>
    </select>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.first_name %></td>
        <td><%= student.last_name %></td>
        <td><% student.teachers.each do |t| %>
        <a href="<%= teacher_path(t.id) %>"><%= t.first_name %> <%= t.last_name %><% end %></a></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student Name</strong>
  <%= @student.first_name %> <%= @student.last_name  %>
</p>

<p>
  <strong>Teacher</strong>
  <% @student.teachers.each do |t| %>
    <a href="<%= teacher_path(t.id) %>"><%= t.first_name %> <%= t.last_name %></a>
  <% end %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_area :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_area :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher Information</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.first_name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.email %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher Name</strong>
  <%= @teacher.first_name %> <%= @teacher.last_name  %>
</p>

<p>
  <strong>Students:</strong>
  <ul>
    <% @teacher.students.each do |student| %>
      <li>
        <a href="<%= student_path(student.id) %>"><%= student.first_name %> <%= student.last_name %></a>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>